---
# control plane nodes
k8s_cp_hosts:
    hosts:
        k8sm1.your.org:
        k8sm2.your.org:
        k8sm3.your.org:
    vars:

# work nodes
k8s_node_hosts:
    hosts:
        k8s10.your.org:
        k8s11.your.org:
    vars:

# all nodes
k8s_hosts:
    children:
        k8s_cp_hosts:
        k8s_node_hosts:

# etcd nodes
k8s_etcd_hosts:
    children:
        k8s_cp_hosts:

# If control plane slb is necessary
k8s_cp_ha_hosts:
    children:
        k8s_cp_hosts:

# If traffic slb is necessary
k8s_traffic_ha_hosts:
    children:
        k8s_node_hosts:

# First(⚠️ Just ONLY one) control plane node
k8s_adm_hosts:
    hosts:
        k8sm1.your.org:
